name: remote ssh command
on: [push]
jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: execute remote git clone
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{secrets.SSH_HOST}}
        username: ${{secrets.SSH_USERNAME}}
        password: ${{secrets.SSH_PASS}}
        script: |
            mkdir test
            cd test
            # git clone git@github.com/bahtyr/champsdb
            echo 'Deployment successful'
