name: Deploy Main

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
      - name: Run deploy script
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
        shell: |
            mkdir test
            cd test
            git clone git@github.com/bahtyr/champsdb
            echo 'Deployment successful'
