name: remote ssh command
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.4
      - name: executing remote ssh commands using password
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASS}}
          
        shell: |
            mkdir test
            cd test
            # git clone git@github.com/bahtyr/champsdb
            echo 'Deployment successful'
